version: 3

tasks:
  install:
    desc: Compile and install the binary locally
    cmds:
      - go build -o ~/.bin/subscrape cmd/scraper/main.go

  run:
    desc: Run stuff
    cmds:
      - go run cmd/scraper/main.go {{.CLI_ARGS}}

  test:
    desc: Run `go test`
    cmds:
      - go tool gotestsum
